name: krg_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  passcode_screen: ^2.0.0
  clipboard: ^0.1.2+5
  get: ^4.1.4
  font_awesome_flutter: ^9.0.0
  expandable: ^5.0.1
  share: ^2.0.2
  web3dart: ^2.1.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  shared_preferences: ^2.0.0
  web_socket_channel: ^2.0.0
  intl: ^0.16.1
  flutter_spinkit: ^5.0.0
  qr_code_scanner: ^0.4.0
  firebase_analytics: ^8.0.4
  url_launcher: ^6.0.2
  flutter_hooks: ^0.16.0
  built_value: ^8.0.6
  built_collection: ^5.0.0
  ed25519_hd_key: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0
  build_runner: ^2.0.2
  built_value_generator: ^8.0.6
  json_serializable: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/image/logo.png
    - images/image/fade.png
    - images/image/profile.jpg
    - images/image/stack.png
    - images/image/header.png
    - images/image/language.png
    - images/empation1.svg
    - images/money.svg
    - images/money1.svg
    - images/share.svg
    - images/stack.svg
    - images/wallet.svg
    - images/transaction-icon.svg
    - images/check.svg
    - images/TargaryenCoin.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
